### ISSUE TITLE
TypeError: unknown filter type: #<Pathname:kindeditor/kindeditor.js>

### ISSUE THREAD

**Issue by Dogzhou** [Macrow/rails_kindeditor#79]
在我把rails 3.2.13 升级到 rails 4.2.1 之后，线上环境的 sass 和 coffee 都读不到了，重新执行 rake assets:precompile RAILS_ENV=production，报错如下：

```
rake aborted!
TypeError: unknown filter type: #<Pathname:kindeditor/kindeditor.js>
/home/deployer/.rbenv/versions/2.1.1/gemsets/xingishere/gems/sprockets-3.3.4/lib/sprockets/legacy.rb:296:in `compile_match_filter'
/home/deployer/.rbenv/versions/2.1.1/gemsets/xingishere/gems/sprockets-3.3.4/lib/sprockets/manifest.rb:125:in `block in find'
/home/deployer/.rbenv/versions/2.1.1/gemsets/xingishere/gems/sprockets-3.3.4/lib/sprockets/manifest.rb:125:in `map'
/home/deployer/.rbenv/versions/2.1.1/gemsets/xingishere/gems/sprockets-3.3.4/lib/sprockets/manifest.rb:125:in `find'
/home/deployer/.rbenv/versions/2.1.1/gemsets/xingishere/gems/sprockets-3.3.4/lib/sprockets/manifest.rb:162:in `compile'
/home/deployer/.rbenv/versions/2.1.1/gemsets/xingishere/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/home/deployer/.rbenv/versions/2.1.1/gemsets/xingishere/gems/sprockets-3.3.4/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/deployer/.rbenv/versions/2.1.1/gemsets/xingishere/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

调了一个下午，仍然未能解决

**Comment by cmingxu** [comment]
遇到同样问题

**Comment by destinyd** [comment]
使用别人fork的，暂时解决了
```ruby
gem 'rails_kindeditor', github: 'javyliu/rails_kindeditor'
```

**Comment by cmingxu** [comment]
@destinyd thx

**Comment by sparkrico** [comment]
https://github.com/Macrow/rails_kindeditor/commit/6208ee49df77cafb8448cf64650e747bffc1dd11
修复了这个问题
